modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/someElseIsHere/sonicboom/issues"
license = "GPL-3.0"

[[mods]]
modId = "sonicboom"
version = "${version}"
displayName = "Sonic Boom"
authors = "thePlaceholder"
description = '''
a useless client side mod
'''
logoFile = "../assets/sonicboom/icon.png"

[[dependencies.sonicboom]]
modId = "neoforge"
type="required"
versionRange = "[21.3.4-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sonicboom]]
modId = "minecraft"
type="required"
versionRange = "[1.21.3,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "sonicboom.mixins.json"
