modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/someElseIsHere/sonicboom/issues"
license = "GPL-3.0"

[[mods]]
modId = "sonicboom"
version = "${version}"
displayName = "Sonic Boom"
authors = "thePlaceholder"
description = '''
a useless client side mod
'''
logoFile = "../assets/sonicboom/icon.png"

[[dependencies.sonicboom]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sonicboom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "sonicboom.mixins.json"
